#!/bin/bash

rpm_tree="${1:-$HOME/rpm}"
version="`./parse-version`"
tarball="allegro-${version}.tar.gz";
src_path="$rpm_tree/SOURCES/${tarball}"
src_sha1="`./parse-sha1 2>/dev/null`"
src_url="http://downloads.sourceforge.net/project/alleg/allegro/${version}/${tarball}"

if [ ! -d "$rpm_tree" ]; then
    echo "Failed to find '$rpm_tree' tree... Trying 'rpmbuild'..." 1>&2
    echo "In the future you can save time by specifying the rpm " 1>&2
    echo "build tree as the first argument to this script." 1>&2
    exec "$0" "`echo $rpm_tree | sed -r 's,\brpm\b,rpmbuild,'`"
fi

if [ -f "$src_path" ]; then
    echo "Source tarball exists... Checking SHA1..."
    if [ "`/usr/bin/sha1sum "$src_path" | awk "/${tarball}/ {print \$1}"`" == "$src_sha1" ]; then
        echo "SHA1 matches..."
        skip_src=1
    else
        echo "SHA1 doesn't match..."
        read -p "Would you like me to fetch the source for you? (Y/n) " answer
        if [ "$answer" != y -a "$answer" != Y ]; then
            skip_src=1
        fi
    fi
fi

if [ "$skip_src" != 1 ]; then
    echo "Fetching source tarball..."
    /usr/bin/wget -O "$src_path" "$src_url"
fi

if [ ! -f SHA1SUM ]; then
    /usr/bin/sha1sum "$src_path" > SHA1SUM
fi

